### ISSUE TITLE
Failed on arm64 mac

### ISSUE THREAD

**Issue by JamesWoolfenden** [inkdrop-org/inkdrop-visualizer#18]
Saved the plan to: plan.out

To perform exactly these actions, run the following command to apply:
    terraform apply "plan.out"
Diagram renderer running on localhost:3000
Computing raw graph...
Processing raw graph...
Chromium not found in cache, downloading...
Downloading Chromium [========================================] 100% 0.0s

  Degraded performance warning:
  Launching Chrome on Mac Silicon (arm64) from an x64 Node installation results in
  Rosetta translating the Chrome binary, even if Chrome is already arm64. This would
  result in huge performance issues. To resolve this, you must run Puppeteer with
  a version of Node built for arm64.
/snapshot/inkdrop-visualizer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:285
                    throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chrome (ver. 121.0.6167.85). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /Users/jwoolfenden/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/snapshot/inkdrop-visualizer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:285:27)
    at ChromeLauncher.executablePath (/snapshot/inkdrop-visualizer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:210:25)
    at ChromeLauncher.computeLaunchArguments (/snapshot/inkdrop-visualizer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:103:37)
    at async ChromeLauncher.launch (/snapshot/inkdrop-visualizer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)

Node.js v18.5.0

**Comment by dant2021** [comment]
Many people seemed to have issues with puppeteer, so we removed it. Try updating inkdrop and running again.
