### ISSUE TITLE
SyntaxError: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by JoyChen1998** [inkdrop-org/inkdrop-visualizer#58]
Hi, I commanded `inkdrop` on my terminal (inkdrop installed by brew.). Then, I got these error:

```
Diagram renderer running on localhost:3000
undefined:1
Terraform v0.12.31
^

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at /snapshot/inkdrop-visualizer/dist/src/index.js:315:32
    at step (/snapshot/inkdrop-visualizer/dist/src/index.js:45:23)
    at Object.next (/snapshot/inkdrop-visualizer/dist/src/index.js:26:53)
    at fulfilled (/snapshot/inkdrop-visualizer/dist/src/index.js:17:58)

Node.js v18.5.0
```

Is it that my version of terraform is too outdated? thanks.

**Comment by JoyChen1998** [comment]
Solved this issue after upgrade my terraform version to 1.5.0. However, when I commanded `inkdrop plan.out`, I met the 2nd issue, the page (localhost:3000) shows nothing on it.
